export const productsList = [
  {
    id: 1,
    title: 'Drukarki paragonowe',
    image: '/images/products/afr.png',
    price: 1299.0,
  },
  {
    id: 2,
    title: 'Oprogramowanie',
    image: '/images/products/agt.png',
    price: 1299.0,
  },
  {
    id: 3,
    title: 'Metkownice',
    image: '/images/products/agu.png',
    price: 1299.0,
  },
  {
    id: 4,
    title: 'Drukarki fiskalne',
    image: '/images/products/agr.png',
    price: 1299.0,
  },
  {
    id: 5,
    title: 'Terminale fiskalne',
    image: '/images/products/agb.png',
    price: 1299.0,
  },
  {
    id: 6,
    title: 'Kasy fiskalne',
    image: '/images/products/afw.png',
    price: 1299.0,
  },
  {
    id: 7,
    title: 'Szuflady',
    image: '/images/products/ahf.png',
    price: 1299.0,
  },
  {
    id: 8,
    title: 'Kolektory',
    image: '/images/products/agx.png',
    price: 1299.0,
  },
  {
    id: 9,
    title: 'Weryfikatory cen',
    image: '/images/products/ahh.png',
    price: 1299.0,
  },
  {
    id: 10,
    title: 'Drukarki kart',
    image: '/images/products/agw.png',
    price: 1299.0,
  },
  {
    id: 11,
    title: 'Systemy POS',
    image: '/images/products/afr.png',
    price: 1299.0,
  },
  {
    id: 12,
    title: 'Drukarki etykiet',
    image: '/images/products/agy.png',
    price: 1299.0,
  },
  {
    id: 13,
    title: 'Czytniki kodów kreskowych',
    image: '/images/products/aga.png',
    price: 1299.0,
  },
  {
    id: 14,
    title: 'Wagi elektroniczne',
    image: '/images/products/ags.png',
    price: 1299.0,
  },
  {
    id: 15,
    title: 'Akcesoria do urządzeń fiskalnych',
    image: '/images/products/afv.png',
    price: 1299.0,
  },
  {
    id: 16,
    title: 'Drukarki fiskalne',
    image: '/images/products/agq.png',
    price: 1299.0,
    isOnlline: true,
  },
  {
    id: 17,
    title: 'Kasy fiskalne',
    image: '/images/products/agf.png',
    price: 1299.0,
    isOnlline: true,
  },
  {
    id: 18,
    title: 'Terminale płatnicze',
    image: '/images/products/ahg.png',
    price: 1299.0,
  },
];
